import type { ClothingBlock, ClothingItem, Day, PersonalDay, PersonalProfile } from "../types";
import { ensureActivityBlockIds, newId } from "./plan";
import { linkLabel, normalizeUrl } from "./links";

export const SQUAD_SIZE = 7;

export const squadActivityRef = (activityBlockId: string, activityIndex: number) =>
  `${activityBlockId}:${activityIndex}`;

export const defaultMemberName = (index: number) => `Person ${index + 1}`;

export const defaultMemberId = (index: number) => `member-${index + 1}`;

export const defaultSquadMemberIds = () =>
  Array.from({ length: SQUAD_SIZE }, (_, i) => defaultMemberId(i));

export const blankClothingItem = (): ClothingItem => ({ text: "" });

export const blankClothingBlock = (n = 1): ClothingBlock => ({
  id: newId("cloth"),
  name: `Outfit ${n}`,
  items: [blankClothingItem()],
  notes: "",
});

export const blankPersonalDay = (): PersonalDay => ({
  id: newId("pday"),
  clothingBlocks: [],
  travelBlocks: [],
  notes: "",
});

/** Mirror squad activities as personal packing blocks (one block per activity row). */
export function reconcilePersonalDayWithSquad(
  personalDay: PersonalDay,
  squadDay?: Day
): PersonalDay {
  if (!squadDay) return personalDay;

  const unlinked = personalDay.clothingBlocks.filter((b) => !b.squadActivityRef);
  const linkedByRef = new Map(
    personalDay.clothingBlocks
      .filter((b) => b.squadActivityRef)
      .map((b) => [b.squadActivityRef!, b])
  );

  const syncedLinked: ClothingBlock[] = [];

  for (const activityBlock of squadDay.activityBlocks) {
    const squadName = activityBlock.name ?? "";
    const link = activityBlock.activities[0]?.text.trim() ?? "";
    if (!squadName.trim() && !link) continue;

    const ref = squadActivityRef(activityBlock.id, 0);
    const defaultName =
      squadName.trim() ? squadName : linkLabel(normalizeUrl(link) ?? link);
    const existing = linkedByRef.get(ref);

    if (existing) {
      syncedLinked.push({
        ...existing,
        squadActivityRef: ref,
        name: existing.name.trim() ? existing.name : defaultName,
      });
    } else {
      syncedLinked.push({
        ...blankClothingBlock(syncedLinked.length + unlinked.length + 1),
        name: defaultName,
        squadActivityRef: ref,
      });
    }
  }

  return {
    ...personalDay,
    clothingBlocks: [...unlinked, ...syncedLinked],
  };
}

export function syncProfilesWithSquadActivities(
  profiles: Record<string, PersonalProfile>,
  squadDays: Day[]
): Record<string, PersonalProfile> {
  const out: Record<string, PersonalProfile> = {};
  for (const [id, profile] of Object.entries(profiles)) {
    out[id] = {
      ...profile,
      days: profile.days.map((personalDay, i) =>
        reconcilePersonalDayWithSquad(personalDay, squadDays[i])
      ),
    };
  }
  return out;
}

export const reconcilePersonalDays = (
  days: PersonalDay[],
  targetLength: number
): PersonalDay[] => {
  if (days.length === targetLength) return days;
  if (days.length < targetLength) {
    return [
      ...days,
      ...Array.from({ length: targetLength - days.length }, blankPersonalDay),
    ];
  }
  return days.slice(0, targetLength);
};

export const ensureProfileIds = (profile: PersonalProfile): PersonalProfile => ({
  ...profile,
  days: profile.days.map((d) => ({
    ...d,
    id: d.id ?? newId("pday"),
    notes: d.notes ?? "",
    travelBlocks: ensureActivityBlockIds(d.travelBlocks ?? []),
    clothingBlocks: (d.clothingBlocks ?? []).map((b) => ({
      ...b,
      id: b.id ?? newId("cloth"),
      notes: b.notes ?? "",
      items: (b.items ?? []).map((item) =>
        typeof item === "string" ? { text: item } : { text: item.text ?? "" }
      ),
    })),
  })),
});

export const createProfile = (
  name: string,
  dayCount: number,
  options?: { hasPasscode?: boolean }
): PersonalProfile =>
  ensureProfileIds({
    id: newId("member"),
    name: name.trim(),
    days: Array.from({ length: dayCount }, blankPersonalDay),
    ...(options?.hasPasscode ? { hasPasscode: true } : {}),
  });

/** No starter profiles — people add their own via the + button. */
export const defaultProfiles = (_dayCount?: number): Record<string, PersonalProfile> => ({});

/** Auto-generated placeholders (Person 1, Person 2, …) — not user-created. */
export function isAutoGeneratedProfile(profile: PersonalProfile): boolean {
  return /^Person \d+$/.test(profile.name.trim());
}

export function stripAutoGeneratedProfiles(
  profiles: Record<string, PersonalProfile>
): Record<string, PersonalProfile> {
  const out: Record<string, PersonalProfile> = {};
  for (const [id, p] of Object.entries(profiles)) {
    if (isAutoGeneratedProfile(p)) continue;
    out[id] = p;
  }
  return out;
}

export const reconcileAllProfiles = (
  profiles: Record<string, PersonalProfile>,
  dayCount: number
): Record<string, PersonalProfile> => {
  const out: Record<string, PersonalProfile> = {};
  for (const id of Object.keys(profiles)) {
    const p = ensureProfileIds(profiles[id]);
    out[id] = { ...p, days: reconcilePersonalDays(p.days, dayCount) };
  }
  return out;
};
