import type { TripSnapshot } from "../services/tripCloud";
import type { Plan } from "../types";
import { planLength, ensureIds } from "./plan";
import { reconcileAllProfiles, stripAutoGeneratedProfiles } from "./personalPlan";

export const OFFLINE_BUNDLE_VERSION = 1;

export interface OfflineTripBundle {
  version: number;
  exportedAt: string;
  title: string;
  snapshot: TripSnapshot;
}

export function buildOfflineBundle(
  snapshot: TripSnapshot,
  title = "Bali Trip"
): OfflineTripBundle {
  return {
    version: OFFLINE_BUNDLE_VERSION,
    exportedAt: new Date().toISOString(),
    title,
    snapshot: JSON.parse(JSON.stringify(snapshot)) as TripSnapshot,
  };
}

export function offlineBundleFilename(title = "Bali Trip"): string {
  const date = new Date().toISOString().slice(0, 10);
  const slug =
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "bali-trip";
  return `${slug}-${date}.btp.json`;
}

export function downloadOfflineBundle(bundle: OfflineTripBundle): void {
  const blob = new Blob([JSON.stringify(bundle, null, 2)], {
    type: "application/json;charset=utf-8",
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = offlineBundleFilename(bundle.title);
  link.rel = "noopener";
  link.click();
  URL.revokeObjectURL(url);
}

export async function parseOfflineBundleFile(file: File): Promise<OfflineTripBundle> {
  const text = await file.text();
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new Error("Invalid backup — file is not valid JSON.");
  }
  return validateOfflineBundle(parsed);
}

function healSnapshot(snapshot: TripSnapshot): TripSnapshot {
  const plans: Record<string, Plan> = {};
  for (const [key, plan] of Object.entries(snapshot.plans ?? {})) {
    plans[key] = ensureIds(plan);
  }

  const planOrder =
    snapshot.planOrder?.filter((name) => plans[name]) ?? Object.keys(plans);
  const activeTemplate =
    snapshot.activeTemplate && plans[snapshot.activeTemplate]
      ? snapshot.activeTemplate
      : (planOrder[0] ?? Object.keys(plans)[0] ?? "Plan 1");

  const loadedPlan = plans[activeTemplate] ?? Object.values(plans)[0];
  const dayCount = loadedPlan ? planLength(loadedPlan) : 5;

  return {
    plans,
    planOrder,
    activeTemplate,
    profiles: snapshot.profiles
      ? reconcileAllProfiles(stripAutoGeneratedProfiles(snapshot.profiles), dayCount)
      : undefined,
  };
}

function validateOfflineBundle(raw: unknown): OfflineTripBundle {
  if (!raw || typeof raw !== "object") {
    throw new Error("Invalid backup file.");
  }

  const record = raw as Record<string, unknown>;

  if (record.plans && record.planOrder) {
    return {
      version: OFFLINE_BUNDLE_VERSION,
      exportedAt: new Date().toISOString(),
      title: "Bali Trip",
      snapshot: healSnapshot(record as unknown as TripSnapshot),
    };
  }

  if (typeof record.version !== "number" || !record.snapshot) {
    throw new Error("Unrecognized backup format.");
  }

  const snapshot = record.snapshot;
  if (!snapshot || typeof snapshot !== "object" || !("plans" in snapshot)) {
    throw new Error("Backup is missing trip data.");
  }

  return {
    version: record.version,
    exportedAt: typeof record.exportedAt === "string" ? record.exportedAt : "",
    title: typeof record.title === "string" ? record.title : "Bali Trip",
    snapshot: healSnapshot(snapshot as TripSnapshot),
  };
}

/** Count embedded PDF attachments in a snapshot (for UI feedback). */
export function countEmbeddedPdfs(snapshot: TripSnapshot): number {
  let count = 0;
  for (const plan of Object.values(snapshot.plans ?? {})) {
    for (const day of plan.days ?? []) {
      if (day.accommodationAttachment?.dataUrl) count += 1;
      for (const block of day.activityBlocks ?? []) {
        if (block.attachment?.dataUrl) count += 1;
      }
    }
  }
  return count;
}
