import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  ThemeProvider,
  CssBaseline,
  Box,
  Paper,
  Stack,
  Typography,
  ToggleButtonGroup,
  ToggleButton,
  TextField,
  Button,
} from "@mui/material";
import ViewWeekIcon from "@mui/icons-material/ViewWeek";
import ViewStreamIcon from "@mui/icons-material/ViewStream";
import LockOutlinedIcon from "@mui/icons-material/LockOutlined";
import {
  DndContext,
  closestCenter,
  PointerSensor,
  useSensor,
  useSensors,
  type DragEndEvent,
} from "@dnd-kit/core";
import {
  SortableContext,
  arrayMove,
  horizontalListSortingStrategy,
} from "@dnd-kit/sortable";

import { buildTheme, tokens } from "./theme";
import { CloudTripBar } from "./components/CloudTripBar";
import { MyPlanView } from "./components/MyPlanView";
import { ProfileUnlockDialog } from "./components/ProfileUnlockDialog";
import { MobileItineraryView } from "./components/MobileItineraryView";
import { DayBlock } from "./components/DayBlock";
import { TripMap } from "./components/TripMap";
import { MapLegend } from "./components/MapLegend";
import { TileSwitcher } from "./components/TileSwitcher";
import { TemplateRow } from "./components/TemplateRow";
import { Splitter } from "./components/Splitter";
import { SortableItem } from "./components/SortableItem";
import { findLoc } from "./locations";
import type {
  CompareLayout,
  Day,
  DocBlock,
  PersonalDay,
  PersonalProfile,
  Plan,
  Stop,
  ThemeMode,
  TileStyle,
  ViewMode,
} from "./types";
import { SQUAD_VIEW_ID } from "./types";
import { addDays, parseISO } from "./utils/date";
import { typingFieldKeyDownProps } from "./utils/keyboard";
import { computeTotalAccommodation } from "./utils/accommodation";
import { blankPlan, ensureIds, planLength, reconcileDays } from "./utils/plan";
import {
  createProfile,
  ensureProfileIds,
  reconcileAllProfiles,
  stripAutoGeneratedProfiles,
  syncProfilesWithSquadActivities,
} from "./utils/personalPlan";
import { usePersistedState } from "./utils/storage";
import { colorForTemplate } from "./utils/palette";
import { useRouteLegs } from "./hooks/useRouteLegs";
import { useCloudTrip } from "./hooks/useCloudTrip";
import { useIsMobile } from "./hooks/useIsMobile";
import { useViewportHeight } from "./hooks/useViewportHeight";
import type { TripSnapshot } from "./services/tripCloud";
import {
  deleteProfilePasscode,
  saveProfilePasscode,
  verifyProfilePasscode,
} from "./services/profilePasscode";

const DEFAULT_TEMPLATE = "Plan 1";
const RADIUS_SECTION = "16px";
const RADIUS_DAY_CARD = "12px";
const MIN_ITINERARY_WIDTH = 360;
const MIN_MAP_WIDTH = 200;
const DEFAULT_LEFT_FRACTION = 0.75;
const PEOPLE_COUNT = 7;
const SNAP_TARGETS = [0.65, 0.75, 0.85];
const SNAP_THRESHOLD = 0.018; // ~1.8% of container width

const unlockedStorageKey = (shareCode: string) => `btp.unlocked.${shareCode}`;

const loadUnlockedProfiles = (shareCode: string | null): Set<string> => {
  if (!shareCode) return new Set();
  try {
    const raw = sessionStorage.getItem(unlockedStorageKey(shareCode));
    if (!raw) return new Set();
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? new Set(parsed.filter((v) => typeof v === "string")) : new Set();
  } catch {
    return new Set();
  }
};

const persistUnlockedProfiles = (shareCode: string, ids: Set<string>) => {
  sessionStorage.setItem(unlockedStorageKey(shareCode), JSON.stringify([...ids]));
};

const clamp = (n: number, min: number, max: number) =>
  Math.max(min, Math.min(max, n));

const snapFraction = (f: number): number => {
  for (const s of SNAP_TARGETS) {
    if (Math.abs(f - s) < SNAP_THRESHOLD) return s;
  }
  return f;
};

export default function App() {
  // -------- Persisted state --------
  const [themeMode] = usePersistedState<ThemeMode>("btp.theme", "light");
  const [mode] = usePersistedState<ViewMode>("btp.mode", "plan");
  const [compareLayout, setCompareLayout] =
    usePersistedState<CompareLayout>("btp.cmpLayout", "stacked");
  const [tile, setTile] = usePersistedState<TileStyle>("btp.tile", "osm");
  const [leftFraction, setLeftFraction] = usePersistedState<number>(
    "btp.split.v3",
    DEFAULT_LEFT_FRACTION
  );
  const [activeTemplate, setActiveTemplate] = usePersistedState<string>(
    "btp.activeTpl",
    DEFAULT_TEMPLATE
  );
  const [plansRaw, setPlansRaw] = usePersistedState<Record<string, Plan>>(
    "btp.plans",
    { [DEFAULT_TEMPLATE]: blankPlan(5) }
  );
  const [planOrder, setPlanOrder] = usePersistedState<string[]>(
    "btp.planOrder",
    [DEFAULT_TEMPLATE]
  );
  const [activeViewId, setActiveViewId] = usePersistedState<string>(
    "btp.activeView",
    SQUAD_VIEW_ID
  );
  const [profilesRaw, setProfilesRaw] = usePersistedState<Record<string, PersonalProfile>>(
    "btp.profiles.v3",
    {}
  );

  // Drop legacy Person 1–7 placeholders from local storage once on load.
  useEffect(() => {
    setProfilesRaw((prev) => {
      const stripped = stripAutoGeneratedProfiles(prev);
      return Object.keys(stripped).length === Object.keys(prev).length
        ? prev
        : stripped;
    });
  }, [setProfilesRaw]);

  // Heal hydrated plans (older snapshots may lack ids / be in old shape).
  const plans = useMemo(() => {
    const out: Record<string, Plan> = {};
    for (const k of Object.keys(plansRaw)) out[k] = ensureIds(plansRaw[k]);
    return out;
  }, [plansRaw]);

  // Make sure activeTemplate stays valid even if it was deleted in a prior session.
  useEffect(() => {
    if (!plans[activeTemplate]) {
      const first = planOrder.find((n) => plans[n]) ?? Object.keys(plans)[0];
      if (first) setActiveTemplate(first);
    }
  }, [plans, planOrder, activeTemplate, setActiveTemplate]);

  const active = plans[activeTemplate] ?? Object.values(plans)[0];
  const activeColor = colorForTemplate(activeTemplate, planOrder);

  const profiles = useMemo(() => {
    const dayCount = active ? planLength(active) : 5;
    const healed: Record<string, PersonalProfile> = {};
    for (const k of Object.keys(profilesRaw)) {
      healed[k] = ensureProfileIds(profilesRaw[k]);
    }
    const lengthReconciled = reconcileAllProfiles(
      stripAutoGeneratedProfiles(healed),
      dayCount
    );
    if (!active) return lengthReconciled;
    return syncProfilesWithSquadActivities(lengthReconciled, active.days);
  }, [profilesRaw, active]);

  // Keep stored profiles aligned when squad trip length changes.
  useEffect(() => {
    if (!active) return;
    const len = planLength(active);
    setProfilesRaw((prev) => {
      const first = Object.values(prev)[0];
      if (first && first.days.length === len) return prev;
      return reconcileAllProfiles(prev, len);
    });
  }, [active?.startDate, active?.endDate, active?.days.length, setProfilesRaw]);

  // Keep personal packing blocks in sync when squad activities change.
  useEffect(() => {
    if (!active) return;
    setProfilesRaw((prev) => {
      const dayCount = planLength(active);
      const lengthReconciled = reconcileAllProfiles(prev, dayCount);
      const synced = syncProfilesWithSquadActivities(lengthReconciled, active.days);
      return JSON.stringify(prev) === JSON.stringify(synced) ? prev : synced;
    });
  }, [active, setProfilesRaw]);

  useEffect(() => {
    if (activeViewId === SQUAD_VIEW_ID) return;
    if (profiles[activeViewId]) return;
    setActiveViewId(SQUAD_VIEW_ID);
  }, [profiles, activeViewId, setActiveViewId]);

  const isSquadView = activeViewId === SQUAD_VIEW_ID;
  const activeProfile = !isSquadView ? profiles[activeViewId] : null;

  const t = tokens(themeMode);
  const theme = useMemo(() => buildTheme(themeMode), [themeMode]);
  const isMobile = useIsMobile();
  useViewportHeight(isMobile);

  const totalAccommodation = useMemo(
    () => computeTotalAccommodation(active?.days ?? []),
    [active]
  );

  const cloudSnapshot = useMemo(
    () => ({ plans, planOrder, activeTemplate, profiles }),
    [plans, planOrder, activeTemplate, profiles]
  );

  const applyCloudSnapshot = useCallback(
    (snapshot: TripSnapshot) => {
      setPlansRaw(snapshot.plans);
      setPlanOrder(snapshot.planOrder);
      setActiveTemplate(snapshot.activeTemplate);
      const loadedPlan =
        snapshot.plans[snapshot.activeTemplate] ??
        Object.values(snapshot.plans)[0];
      const dayCount = loadedPlan ? planLength(loadedPlan) : 5;
      if (snapshot.profiles) {
        setProfilesRaw(
          reconcileAllProfiles(
            stripAutoGeneratedProfiles(snapshot.profiles),
            dayCount
          )
        );
      }
    },
    [setPlansRaw, setPlanOrder, setActiveTemplate, setProfilesRaw]
  );

  const cloud = useCloudTrip({
    snapshot: cloudSnapshot,
    applySnapshot: applyCloudSnapshot,
    tripTitle: "Bali Trip",
  });

  const [unlockedProfileIds, setUnlockedProfileIds] = useState<Set<string>>(() =>
    loadUnlockedProfiles(cloud.shareCode)
  );
  const [unlockOpen, setUnlockOpen] = useState(false);
  const [pendingViewId, setPendingViewId] = useState<string | null>(null);
  const [unlocking, setUnlocking] = useState(false);

  useEffect(() => {
    setUnlockedProfileIds(loadUnlockedProfiles(cloud.shareCode));
  }, [cloud.shareCode]);

  const markProfileUnlocked = useCallback(
    (profileId: string) => {
      if (!cloud.shareCode) return;
      setUnlockedProfileIds((prev) => {
        const next = new Set(prev);
        next.add(profileId);
        persistUnlockedProfiles(cloud.shareCode!, next);
        return next;
      });
    },
    [cloud.shareCode]
  );

  const isProfileUnlocked = useCallback(
    (profileId: string) => {
      const profile = profiles[profileId];
      if (!profile?.hasPasscode) return true;
      return unlockedProfileIds.has(profileId);
    },
    [profiles, unlockedProfileIds]
  );

  const handleActiveViewChange = (viewId: string) => {
    if (viewId === SQUAD_VIEW_ID) {
      setActiveViewId(SQUAD_VIEW_ID);
      return;
    }

    const profile = profiles[viewId];
    if (!profile) return;

    if (profile.hasPasscode && !isProfileUnlocked(viewId)) {
      setPendingViewId(viewId);
      setUnlockOpen(true);
      return;
    }

    setActiveViewId(viewId);
  };

  const handleUnlockProfile = async (pin: string): Promise<boolean> => {
    if (!pendingViewId || !cloud.shareCode) return false;

    setUnlocking(true);
    try {
      const ok = await verifyProfilePasscode(cloud.shareCode, pendingViewId, pin);
      if (!ok) return false;

      markProfileUnlocked(pendingViewId);
      setActiveViewId(pendingViewId);
      setUnlockOpen(false);
      setPendingViewId(null);
      return true;
    } finally {
      setUnlocking(false);
    }
  };

  const closeUnlockDialog = () => {
    setUnlockOpen(false);
    setPendingViewId(null);
  };

  // -------- Plan-level mutations --------
  const setPlans = setPlansRaw;
  const updatePlan = (name: string, patch: Partial<Plan>) =>
    setPlans((prev) => ({ ...prev, [name]: { ...prev[name], ...patch } }));

  const setActiveStartDate = (v: string) => {
    setPlans((prev) => {
      const p = prev[activeTemplate];
      const newEnd = parseISO(v) > parseISO(p.endDate) ? v : p.endDate;
      const updated: Plan = { ...p, startDate: v, endDate: newEnd };
      updated.days = reconcileDays(p.days, planLength(updated));
      return { ...prev, [activeTemplate]: updated };
    });
  };

  const setActiveEndDate = (v: string) => {
    setPlans((prev) => {
      const p = prev[activeTemplate];
      if (parseISO(v) < parseISO(p.startDate)) return prev;
      const updated: Plan = { ...p, endDate: v };
      updated.days = reconcileDays(p.days, planLength(updated));
      return { ...prev, [activeTemplate]: updated };
    });
  };

  const updateDayInPlan = (planName: string, id: string, day: Day) =>
    setPlans((prev) => {
      const plan = prev[planName];
      if (!plan) return prev;
      return {
        ...prev,
        [planName]: {
          ...plan,
          days: plan.days.map((d) => (d.id === id ? day : d)),
        },
      };
    });

  const reorderDaysInPlan = (planName: string, fromId: string, toId: string) => {
    const days = plans[planName].days;
    const oldIdx = days.findIndex((d) => d.id === fromId);
    const newIdx = days.findIndex((d) => d.id === toId);
    if (oldIdx < 0 || newIdx < 0) return;
    updatePlan(planName, { days: arrayMove(days, oldIdx, newIdx) });
  };

  const updateProfile = (profile: PersonalProfile) =>
    setProfilesRaw((prev) => ({ ...prev, [profile.id]: profile }));

  const updateProfileDay = (profileId: string, dayId: string, day: PersonalDay) =>
    setProfilesRaw((prev) => {
      const profile = prev[profileId];
      if (!profile) return prev;
      return {
        ...prev,
        [profileId]: {
          ...profile,
          days: profile.days.map((d) => (d.id === dayId ? day : d)),
        },
      };
    });

  const updateProfileDocBlocks = (profileId: string, docBlocks: DocBlock[]) =>
    setProfilesRaw((prev) => {
      const profile = prev[profileId];
      if (!profile) return prev;
      return {
        ...prev,
        [profileId]: {
          ...profile,
          docBlocks,
        },
      };
    });

  const addProfile = async (
    name: string,
    passcode?: string,
    options?: { shareCode?: string }
  ): Promise<{ ok: boolean; error?: string }> => {
    const trimmed = name.trim();
    if (!trimmed) return { ok: false, error: "Name is required." };

    const shareCodeForPasscode = options?.shareCode ?? cloud.shareCode;

    if (passcode && !shareCodeForPasscode) {
      return { ok: false, error: "Share this trip first to enable profile passcodes." };
    }

    const profile = createProfile(trimmed, planLength(active), {
      hasPasscode: !!passcode,
    });

    if (passcode && shareCodeForPasscode) {
      try {
        await saveProfilePasscode(shareCodeForPasscode, profile.id, passcode);
      } catch (err: unknown) {
        const message =
          err instanceof Error ? err.message : "Could not save profile passcode.";
        return { ok: false, error: message };
      }
    }

    setProfilesRaw((prev) => ({ ...prev, [profile.id]: profile }));
    markProfileUnlocked(profile.id);
    setActiveViewId(profile.id);
    return { ok: true };
  };

  const renameProfile = (id: string, name: string) => {
    const trimmed = name.trim();
    if (!trimmed || !profiles[id]) return;
    setProfilesRaw((prev) => ({
      ...prev,
      [id]: { ...prev[id], name: trimmed },
    }));
  };

  const deleteProfile = async (id: string) => {
    if (cloud.shareCode && profiles[id]?.hasPasscode) {
      try {
        await deleteProfilePasscode(cloud.shareCode, id);
      } catch {
        // Profile data is removed locally even if cloud passcode cleanup fails.
      }
    }

    setProfilesRaw((prev) => {
      const out = { ...prev };
      delete out[id];
      return out;
    });

    if (cloud.shareCode) {
      setUnlockedProfileIds((prev) => {
        if (!prev.has(id)) return prev;
        const next = new Set(prev);
        next.delete(id);
        persistUnlockedProfiles(cloud.shareCode!, next);
        return next;
      });
    }

    if (activeViewId === id) setActiveViewId(SQUAD_VIEW_ID);
  };

  // -------- Splitter handlers --------
  const containerRef = useRef<HTMLDivElement | null>(null);
  const handleSplitterDrag = (deltaX: number) => {
    const w = containerRef.current?.getBoundingClientRect().width;
    if (!w) return;
    const usable = w - 16;
    const minFrac = MIN_ITINERARY_WIDTH / usable;
    const maxFrac = 1 - MIN_MAP_WIDTH / usable;
    setLeftFraction((prev) => {
      const next = clamp(prev + deltaX / usable, minFrac, maxFrac);
      return snapFraction(next);
    });
  };
  const resetSplit = () => setLeftFraction(DEFAULT_LEFT_FRACTION);

  // -------- Map stops + hover-link + OSRM --------
  const [hoveredDayIndex, setHoveredDayIndex] = useState<number | null>(null);
  const dayCardRefs = useRef<Record<string, HTMLDivElement | null>>({});

  const stops: Stop[] = useMemo(() => {
    if (!active) return [];
    const out: Stop[] = [];
    let counter = 1;
    active.days.forEach((d, i) => {
      const place = findLoc(d.place);
      if (place) {
        out.push({
          kind: "place",
          label: String(counter++),
          name: `Day ${i + 1} – ${place.name}`,
          coords: place.coords,
          dayIndex: i,
        });
      }
      const ender = findLoc(d.endPlace);
      if (ender && (!place || ender.name !== place.name)) {
        out.push({
          kind: "end",
          label: String(counter++),
          name: `Day ${i + 1} ends at ${ender.name}`,
          coords: ender.coords,
          dayIndex: i,
        });
      }
    });
    return out;
  }, [active]);

  const legs = useRouteLegs(stops);

  const handleMarkerClick = (dayIndex: number) => {
    const d = active.days[dayIndex];
    if (!d) return;
    const el = dayCardRefs.current[d.id];
    if (el) {
      el.scrollIntoView({ behavior: "smooth", inline: "center", block: "nearest" });
      setHoveredDayIndex(dayIndex);
      window.setTimeout(() => setHoveredDayIndex(null), 1500);
    }
  };

  const showPersonalPlan =
    !isSquadView && !!activeProfile && isProfileUnlocked(activeProfile.id);
  const pendingUnlockProfile = pendingViewId ? profiles[pendingViewId] : null;

  useEffect(() => {
    if (isSquadView || !activeProfile?.hasPasscode) return;
    if (isProfileUnlocked(activeProfile.id)) return;
    setPendingViewId(activeProfile.id);
    setUnlockOpen(true);
  }, [activeProfile, isProfileUnlocked, isSquadView]);

  // -------- Render --------
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Box
        sx={{
          p: isMobile ? 0 : { xs: 1.5, md: 2.5 },
          ...(isMobile
            ? {
                position: "fixed",
                top: "var(--app-offset-top, 0px)",
                left: 0,
                right: 0,
                height: "var(--app-height, 100dvh)",
                maxHeight: "var(--app-height, 100dvh)",
              }
            : { height: "100vh" }),
          display: "flex",
          flexDirection: "column",
          gap: isMobile ? 0 : 2,
          bgcolor: "background.default",
          overflow: "hidden",
        }}
      >
        {!isMobile ? (
        <CloudTripBar
          configured={cloud.configured}
          shareCode={cloud.shareCode}
          syncStatus={cloud.syncStatus}
          error={cloud.error}
          themeMode={themeMode}
          activeViewId={activeViewId}
          profiles={profiles}
          totalAccommodation={totalAccommodation}
          peopleCount={PEOPLE_COUNT}
          onActiveViewChange={handleActiveViewChange}
          onAddProfile={addProfile}
          onRenameProfile={renameProfile}
          onDeleteProfile={(id) => void deleteProfile(id)}
          onCreateSharedTrip={cloud.createSharedTrip}
          onStopSharing={cloud.stopSharing}
        />
        ) : null}

        <ProfileUnlockDialog
          open={unlockOpen}
          profileName={pendingUnlockProfile?.name ?? "Profile"}
          verifying={unlocking}
          onClose={closeUnlockDialog}
          onUnlock={handleUnlockProfile}
        />

        {isMobile ? (
          !isSquadView && activeProfile?.hasPasscode && !isProfileUnlocked(activeProfile.id) ? (
            <Paper
              elevation={0}
              sx={{
                flex: 1,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                borderRadius: 0,
                boxShadow: "none",
                mx: 1.5,
                my: 1.5,
              }}
            >
              <Stack spacing={1.5} sx={{ alignItems: "center", maxWidth: 360, px: 2 }}>
                <LockOutlinedIcon sx={{ fontSize: 40, opacity: 0.7 }} />
                <Typography variant="h6" sx={{ fontWeight: 700 }}>
                  {activeProfile.name}&apos;s plan is locked
                </Typography>
                <Typography variant="body2" sx={{ color: "text.secondary", textAlign: "center" }}>
                  Enter the 4-digit passcode to view this personal plan.
                </Typography>
                <Button
                  variant="contained"
                  onClick={() => {
                    setPendingViewId(activeProfile.id);
                    setUnlockOpen(true);
                  }}
                >
                  Enter passcode
                </Button>
              </Stack>
            </Paper>
          ) : mode === "plan" ? (
            <MobileItineraryView
              plan={active}
              snapshot={cloudSnapshot}
              themeMode={themeMode}
              activeViewId={activeViewId}
              profiles={profiles}
              activeProfile={activeProfile}
              showPersonalPlan={showPersonalPlan}
              onActiveViewChange={handleActiveViewChange}
              onUpdateDay={(id, d) => updateDayInPlan(activeTemplate, id, d)}
              onUpdateProfileDay={updateProfileDay}
              onUpdateProfileDocBlocks={updateProfileDocBlocks}
              onImportSnapshot={applyCloudSnapshot}
            />
          ) : (
            <Paper
              elevation={0}
              sx={{
                flex: 1,
                m: 1.5,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                borderRadius: "16px",
                boxShadow: t.cardShadow,
              }}
            >
              <Typography sx={{ color: "text.secondary", px: 2, textAlign: "center" }}>
                Compare mode is available on desktop.
              </Typography>
            </Paper>
          )
        ) : showPersonalPlan && activeProfile ? (
          <MyPlanView
            profile={activeProfile}
            squadPlan={active}
            themeMode={themeMode}
            tile={tile}
            leftFraction={leftFraction}
            splitContainerRef={containerRef}
            onSplitterDrag={handleSplitterDrag}
            onResetSplit={resetSplit}
            onUpdateProfile={updateProfile}
            onUpdateProfileDocBlocks={updateProfileDocBlocks}
          />
        ) : !isSquadView && activeProfile?.hasPasscode ? (
          <Paper
            elevation={0}
            sx={{
              flex: 1,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              borderRadius: RADIUS_SECTION,
              boxShadow: t.cardShadow,
            }}
          >
            <Stack spacing={1.5} sx={{ alignItems: "center", maxWidth: 360, px: 2 }}>
              <LockOutlinedIcon sx={{ fontSize: 40, opacity: 0.7 }} />
              <Typography variant="h6" sx={{ fontWeight: 700 }}>
                {activeProfile.name}&apos;s plan is locked
              </Typography>
              <Typography variant="body2" sx={{ color: "text.secondary", textAlign: "center" }}>
                Enter the 4-digit passcode to view this personal plan.
              </Typography>
              <Button
                variant="contained"
                onClick={() => {
                  setPendingViewId(activeProfile.id);
                  setUnlockOpen(true);
                }}
              >
                Enter passcode
              </Button>
            </Stack>
          </Paper>
        ) : mode === "plan" ? (
          <PlanView
            ref={containerRef}
            plan={active}
            color={activeColor}
            tile={tile}
            stops={stops}
            legs={legs}
            themeMode={themeMode}
            hoveredDayIndex={hoveredDayIndex}
            onHoverDayIndex={setHoveredDayIndex}
            onMarkerClick={handleMarkerClick}
            onTileChange={setTile}
            leftFraction={leftFraction}
            onSplitterDrag={handleSplitterDrag}
            onResetSplit={resetSplit}
            onUpdateDay={(id, d) => updateDayInPlan(activeTemplate, id, d)}
            onReorderDays={(fromId, toId) =>
              reorderDaysInPlan(activeTemplate, fromId, toId)
            }
            registerDayRef={(id, el) => {
              dayCardRefs.current[id] = el;
            }}
            startDate={active.startDate}
            endDate={active.endDate}
            onStartDateChange={setActiveStartDate}
            onEndDateChange={setActiveEndDate}
          />
        ) : (
          <CompareView
            planOrder={planOrder}
            plans={plans}
            activeTemplate={activeTemplate}
            themeMode={themeMode}
            layout={compareLayout}
            onLayoutChange={setCompareLayout}
            onUpdatePlan={updatePlan}
            onActivateTemplate={setActiveTemplate}
            sectionRadius={RADIUS_SECTION}
            tokensVal={t}
          />
        )}
      </Box>
    </ThemeProvider>
  );
}

// =====================================================================
// Plan-mode (resizable split: editable cards | map)
// =====================================================================

interface PlanViewProps {
  plan: Plan;
  color: string;
  tile: TileStyle;
  stops: Stop[];
  legs: ReturnType<typeof useRouteLegs>;
  themeMode: ThemeMode;
  hoveredDayIndex: number | null;
  leftFraction: number;
  onHoverDayIndex: (i: number | null) => void;
  onMarkerClick: (dayIndex: number) => void;
  onTileChange: (s: TileStyle) => void;
  onSplitterDrag: (dx: number) => void;
  onResetSplit: () => void;
  onUpdateDay: (id: string, day: Day) => void;
  onReorderDays: (fromId: string, toId: string) => void;
  registerDayRef: (id: string, el: HTMLDivElement | null) => void;
  startDate: string;
  endDate: string;
  onStartDateChange: (v: string) => void;
  onEndDateChange: (v: string) => void;
}

const PlanView = ({
  ref,
  plan,
  color,
  tile,
  stops,
  legs,
  themeMode,
  hoveredDayIndex,
  leftFraction,
  onHoverDayIndex,
  onMarkerClick,
  onTileChange,
  onSplitterDrag,
  onResetSplit,
  onUpdateDay,
  onReorderDays,
  registerDayRef,
  startDate,
  endDate,
  onStartDateChange,
  onEndDateChange,
}: PlanViewProps & { ref?: React.Ref<HTMLDivElement> }) => {
  const t = tokens(themeMode);
  const dateBase = parseISO(plan.startDate);

  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 5 } })
  );
  const onDragEnd = (e: DragEndEvent) => {
    const { active, over } = e;
    if (!over || active.id === over.id) return;
    onReorderDays(active.id as string, over.id as string);
  };

  return (
    <Box
      ref={ref}
      sx={{
        flex: 1,
        minHeight: 0,
        display: "flex",
      }}
    >
      <Box
        sx={{
          flex: leftFraction,
          minWidth: MIN_ITINERARY_WIDTH,
          minHeight: 0,
          display: "flex",
          flexDirection: "column",
        }}
      >
        <Paper
          elevation={0}
          sx={{
            flex: 1,
            p: 2,
            borderRadius: RADIUS_SECTION,
            boxShadow: t.cardShadow,
            display: "flex",
            flexDirection: "column",
            minHeight: 0,
            minWidth: 0,
            overflow: "hidden",
          }}
        >
          <Stack
            direction="row"
            sx={{
              flexShrink: 0,
              pb: 1.25,
              mb: 1,
              alignItems: "center",
              justifyContent: "space-between",
              flexWrap: "wrap",
              gap: 1,
            }}
          >
            <Stack direction="row" spacing={1} sx={{ alignItems: "center" }}>
              <Box
                sx={{
                  width: 12,
                  height: 12,
                  borderRadius: "50%",
                  bgcolor: color,
                  border: "2px solid #fff",
                  boxShadow: `0 2px 6px ${color}66`,
                }}
              />
              <Typography variant="h6">Bali itinerary</Typography>
            </Stack>
            <Stack direction="row" spacing={1} sx={{ alignItems: "center", flexWrap: "wrap" }}>
              <TextField
                size="small"
                type="date"
                value={startDate}
                onChange={(e) => {
                  const v = e.target.value;
                  onStartDateChange(v);
                  if (parseISO(v) > parseISO(endDate)) onEndDateChange(v);
                }}
                {...typingFieldKeyDownProps}
                sx={{ width: 142 }}
              />
              <Typography sx={{ color: "text.secondary", fontSize: 13 }}>→</Typography>
              <TextField
                size="small"
                type="date"
                value={endDate}
                onChange={(e) => {
                  const v = e.target.value;
                  if (parseISO(v) < parseISO(startDate)) return;
                  onEndDateChange(v);
                }}
                {...typingFieldKeyDownProps}
                sx={{ width: 142 }}
              />
              <Typography variant="body2" sx={{ color: "text.secondary" }}>
                {plan.days.length} day{plan.days.length > 1 ? "s" : ""}
              </Typography>
            </Stack>
          </Stack>

          <Box
            sx={{
              flex: 1,
              minHeight: 0,
              display: "flex",
              flexDirection: "column",
            }}
          >
            <DndContext
              sensors={sensors}
              collisionDetection={closestCenter}
              onDragEnd={onDragEnd}
            >
              <SortableContext
                items={plan.days.map((d) => d.id)}
                strategy={horizontalListSortingStrategy}
              >
                <Box
                  sx={{
                    display: "flex",
                    gap: 1.5,
                    overflowX: "auto",
                    overflowY: "visible",
                    pb: 1,
                    flex: 1,
                    alignItems: "stretch",
                    minWidth: 0,
                    minHeight: 0,
                    scrollbarGutter: "stable",
                  }}
                >
                  {plan.days.map((day, i) => (
                    <SortableItem key={day.id} id={day.id} fill>
                      {(handle) => (
                        <Box
                          ref={(el: HTMLDivElement | null) =>
                            registerDayRef(day.id, el)
                          }
                          sx={{ height: "100%" }}
                        >
                          <DayBlock
                            index={i}
                            date={addDays(dateBase, i)}
                            day={day}
                            mode={themeMode}
                            cardRadius={RADIUS_DAY_CARD}
                            dragHandle={handle}
                            onHover={(h) => onHoverDayIndex(h ? i : null)}
                            onChange={(d) => onUpdateDay(day.id, d)}
                          />
                        </Box>
                      )}
                    </SortableItem>
                  ))}
                </Box>
              </SortableContext>
            </DndContext>
          </Box>
        </Paper>
      </Box>

      <Splitter onDrag={onSplitterDrag} onDoubleClick={onResetSplit} />

      <Box
        sx={{
          flex: 1 - leftFraction,
          minWidth: MIN_MAP_WIDTH,
          minHeight: 0,
          display: "flex",
          flexDirection: "column",
        }}
      >
        <Paper
          elevation={0}
          sx={{
            flex: 1,
            p: 0,
            borderRadius: RADIUS_SECTION,
            boxShadow: t.cardShadow,
            overflow: "hidden",
            minHeight: 0,
            minWidth: 0,
            position: "relative",
          }}
        >
          <TripMap
            stops={stops}
            color={color}
            tile={tile}
            legs={legs}
            hoveredDayIndex={hoveredDayIndex}
            onMarkerClick={onMarkerClick}
          />
          <MapLegend color={color} />
          <TileSwitcher value={tile} onChange={onTileChange} />
        </Paper>
      </Box>
    </Box>
  );
};

// =====================================================================
// Compare-mode (templates stacked OR side-by-side)
// =====================================================================

interface CompareViewProps {
  planOrder: string[];
  plans: Record<string, Plan>;
  activeTemplate: string;
  themeMode: ThemeMode;
  layout: CompareLayout;
  onLayoutChange: (l: CompareLayout) => void;
  onUpdatePlan: (name: string, patch: Partial<Plan>) => void;
  onActivateTemplate: (name: string) => void;
  sectionRadius: string;
  tokensVal: ReturnType<typeof tokens>;
}

function CompareView({
  planOrder,
  plans,
  activeTemplate,
  themeMode,
  layout,
  onLayoutChange,
  onUpdatePlan,
  onActivateTemplate,
  sectionRadius,
  tokensVal: t,
}: CompareViewProps) {
  return (
    <Paper
      elevation={0}
      sx={{
        p: 2.5,
        borderRadius: sectionRadius,
        boxShadow: t.cardShadow,
        flex: 1,
        minHeight: 0,
        overflow: "hidden",
        display: "flex",
        flexDirection: "column",
      }}
    >
      <Stack
        direction="row"
        sx={{
          mb: 2,
          alignItems: "center",
          justifyContent: "space-between",
        }}
      >
        <Typography variant="h6">Compare templates</Typography>
        <ToggleButtonGroup
          size="small"
          exclusive
          value={layout}
          onChange={(_, v: CompareLayout | null) => v && onLayoutChange(v)}
          sx={{
            "& .MuiToggleButton-root": {
              textTransform: "none",
              fontSize: 12,
              px: 1.25,
              py: 0.5,
              borderColor: t.innerBorder,
              color: "text.secondary",
              "&.Mui-selected": {
                bgcolor: "primary.main",
                color: "#fff",
                "&:hover": { bgcolor: "primary.dark" },
              },
            },
          }}
        >
          <ToggleButton value="stacked">
            <ViewStreamIcon sx={{ fontSize: 16, mr: 0.5 }} />
            Stacked
          </ToggleButton>
          <ToggleButton value="side-by-side">
            <ViewWeekIcon sx={{ fontSize: 16, mr: 0.5 }} />
            Side by side
          </ToggleButton>
        </ToggleButtonGroup>
      </Stack>

      <Box
        sx={{
          flex: 1,
          minHeight: 0,
          display: "flex",
          flexDirection: layout === "side-by-side" ? "row" : "column",
          gap: layout === "side-by-side" ? 2 : 0,
          overflow: layout === "side-by-side" ? "auto" : "auto",
        }}
      >
        {planOrder.map((name) => (
          <TemplateRow
            key={name}
            name={name}
            plan={plans[name]}
            active={name === activeTemplate}
            cardRadius={RADIUS_DAY_CARD}
            color={colorForTemplate(name, planOrder)}
            mode={themeMode}
            layout={layout === "side-by-side" ? "column" : "row"}
            onChange={(p) => onUpdatePlan(name, p)}
            onActivate={() => onActivateTemplate(name)}
          />
        ))}
      </Box>
    </Paper>
  );
}
